{
 "title": "Ava-1",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "bs",
    "query": {
     "query": "label_values(bender_metrics_book_delay_gw_to_publisher_raw,bs)"
    }
   },
   {
    "name": "gateway",
    "query": {
     "query": "label_values(bender_metrics_book_delay_gw_to_publisher_raw{bs=\"$bs\"},gateway)"
    }
   },
   {
    "name": "robots",
    "query": {
     "query": "label_values(bender_metrics_robot_timings_metrics_pre_cycle_raw{bs=\"$bs\"},robot)"
    }
   },
   {
    "name": "interval",
    "label": "Time Interval",
    "query": "1m,5m,10m,30m,1h,4h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "gateway_to_publisher",
   "type": "candlestick",
   "description": "Start: Получения в гейте сырого пакета с маркет датой.\n\nProcess: Парсинг пакета и формирование книги.\nОпционально возможен SSL.\n\nEnd: Маркет дата готова к публикации.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "quantile_over_time(1, bender_metrics_book_delay_gw_to_publisher_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor\nquantile_over_time(1, bs_book_delay_gw_to_publisher_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p100"
    },
    {
     "expr": "quantile_over_time(0.99, bender_metrics_book_delay_gw_to_publisher_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor\nquantile_over_time(0.99, bs_book_delay_gw_to_publisher_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p99"
    },
    {
     "expr": "quantile_over_time(0.95, bender_metrics_book_delay_gw_to_publisher_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor\nquantile_over_time(0.95, bs_book_delay_gw_to_publisher_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p95"
    },
    {
     "expr": "quantile_over_time(0.75, bender_metrics_book_delay_gw_to_publisher_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor\nquantile_over_time(0.75, bs_book_delay_gw_to_publisher_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p75"
    },
    {
     "expr": "quantile_over_time(0.5, bender_metrics_book_delay_gw_to_publisher_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor\nquantile_over_time(0.5, bs_book_delay_gw_to_publisher_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p50"
    },
    {
     "expr": "quantile_over_time(0.25, bender_metrics_book_delay_gw_to_publisher_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor\nquantile_over_time(0.25, bs_book_delay_gw_to_publisher_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p25"
    },
    {
     "expr": "quantile_over_time(0.05, bender_metrics_book_delay_gw_to_publisher_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor\nquantile_over_time(0.05, bs_book_delay_gw_to_publisher_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p05"
    },
    {
     "expr": "quantile_over_time(0.01, bender_metrics_book_delay_gw_to_publisher_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor\nquantile_over_time(0.01, bs_book_delay_gw_to_publisher_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p01"
    }
   ]
  },
  {
   "title": "publisher_to robot",
   "type": "candlestick",
   "description": "Start: Маркет дата готова к публикации.\n\nProcess: Уведомление робота о новой маркет дате, планирование его запуска и ожидание конца обработки всех ранее запланированных роботов.\n\nEnd: Начало цикла робота.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "quantile_over_time(1, bender_metrics_publisher_to_robot_book_delay_raw{bs=\"$bs\"}[$__interval])\nor\nquantile_over_time(1, bs_publisher_to_robot_book_delay_raw{bs=\"$bs\"}[$__interval])",
     "legendFormat": "p100"
    },
    {
     "expr": "quantile_over_time(0.99, bender_metrics_publisher_to_robot_book_delay_raw{bs=\"$bs\"}[$__interval])\nor\nquantile_over_time(0.99, bs_publisher_to_robot_book_delay_raw{bs=\"$bs\"}[$__interval])",
     "legendFormat": "p99"
    },
    {
     "expr": "quantile_over_time(0.95, bender_metrics_publisher_to_robot_book_delay_raw{bs=\"$bs\"}[$__interval])\nor\nquantile_over_time(0.95, bs_publisher_to_robot_book_delay_raw{bs=\"$bs\"}[$__interval])",
     "legendFormat": "p95"
    },
    {
     "expr": "quantile_over_time(0.75, bender_metrics_publisher_to_robot_book_delay_raw{bs=\"$bs\"}[$__interval])\nor\nquantile_over_time(0.75, bs_publisher_to_robot_book_delay_raw{bs=\"$bs\"}[$__interval])",
     "legendFormat": "p75"
    },
    {
     "expr": "quantile_over_time(0.5, bender_metrics_publisher_to_robot_book_delay_raw{bs=\"$bs\"}[$__interval])\nor\nquantile_over_time(0.5, bs_publisher_to_robot_book_delay_raw{bs=\"$bs\"}[$__interval])",
     "legendFormat": "p50"
    },
    {
     "expr": "quantile_over_time(0.25, bender_metrics_publisher_to_robot_book_delay_raw{bs=\"$bs\"}[$__interval])\nor\nquantile_over_time(0.25, bs_publisher_to_robot_book_delay_raw{bs=\"$bs\"}[$__interval])",
     "legendFormat": "p25"
    },
    {
     "expr": "quantile_over_time(0.05, bender_metrics_publisher_to_robot_book_delay_raw{bs=\"$bs\"}[$__interval])\nor\nquantile_over_time(0.05, bs_publisher_to_robot_book_delay_raw{bs=\"$bs\"}[$__interval])",
     "legendFormat": "p05"
    },
    {
     "expr": "quantile_over_time(0.01, bender_metrics_publisher_to_robot_book_delay_raw{bs=\"$bs\"}[$__interval])\nor\nquantile_over_time(0.01, bs_publisher_to_robot_book_delay_raw{bs=\"$bs\"}[$__interval])",
     "legendFormat": "p01"
    }
   ]
  },
  {
   "title": "pre_cycle",
   "type": "candlestick",
   "description": "Start: Запуск цикла.\n\nProcess: Подготовка к запуску основного цикла робота. \nОбработка пришедших ивентов, выполнение робот-транферов, расчет переменных.\n\nEnd: Начало основного цикла робота.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "quantile_over_time(1, bender_metrics_robot_timings_metrics_pre_cycle_raw{bs=\"$bs\", robot=\"$robots\"}[$__interval])\nor \nquantile_over_time(1, bs_robot_timings_metrics_pre_cycle_raw{bs=\"$bs\", robot=\"$robots\"}[$__interval])",
     "legendFormat": "p100"
    },
    {
     "expr": "quantile_over_time(0.99, bender_metrics_robot_timings_metrics_pre_cycle_raw{bs=\"$bs\", robot=\"$robots\"}[$__interval])\nor \nquantile_over_time(0.99, bs_robot_timings_metrics_pre_cycle_raw{bs=\"$bs\", robot=\"$robots\"}[$__interval])",
     "legendFormat": "p99"
    },
    {
     "expr": "quantile_over_time(0.95, bender_metrics_robot_timings_metrics_pre_cycle_raw{bs=\"$bs\", robot=\"$robots\"}[$__interval])\nor \nquantile_over_time(0.95, bs_robot_timings_metrics_pre_cycle_raw{bs=\"$bs\", robot=\"$robots\"}[$__interval])",
     "legendFormat": "p95"
    },
    {
     "expr": "quantile_over_time(0.75, bender_metrics_robot_timings_metrics_pre_cycle_raw{bs=\"$bs\", robot=\"$robots\"}[$__interval])\nor \nquantile_over_time(0.75, bs_robot_timings_metrics_pre_cycle_raw{bs=\"$bs\", robot=\"$robots\"}[$__interval])",
     "legendFormat": "p75"
    },
    {
     "expr": "quantile_over_time(0.50, bender_metrics_robot_timings_metrics_pre_cycle_raw{bs=\"$bs\", robot=\"$robots\"}[$__interval])\nor \nquantile_over_time(0.50, bs_robot_timings_metrics_pre_cycle_raw{bs=\"$bs\", robot=\"$robots\"}[$__interval])",
     "legendFormat": "p50"
    },
    {
     "expr": "quantile_over_time(0.25, bender_metrics_robot_timings_metrics_pre_cycle_raw{bs=\"$bs\", robot=\"$robots\"}[$__interval])\nor \nquantile_over_time(0.25, bs_robot_timings_metrics_pre_cycle_raw{bs=\"$bs\", robot=\"$robots\"}[$__interval])",
     "legendFormat": "p25"
    },
    {
     "expr": "quantile_over_time(0.05, bender_metrics_robot_timings_metrics_pre_cycle_raw{bs=\"$bs\", robot=\"$robots\"}[$__interval])\nor \nquantile_over_time(0.05, bs_robot_timings_metrics_pre_cycle_raw{bs=\"$bs\", robot=\"$robots\"}[$__interval])",
     "legendFormat": "p05"
    },
    {
     "expr": "quantile_over_time(0.01, bender_metrics_robot_timings_metrics_pre_cycle_raw{bs=\"$bs\", robot=\"$robots\"}[$__interval])\nor \nquantile_over_time(0.01, bs_robot_timings_metrics_pre_cycle_raw{bs=\"$bs\", robot=\"$robots\"}[$__interval])",
     "legendFormat": "p01"
    }
   ]
  },
  {
   "title": "cycle",
   "type": "candlestick",
   "description": "Start: Начало выполнения основного цикла робота. \n\nProcess: Торговая логика.\n\nEnd: Решения по торговле приняты. ",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "quantile_over_time(1, bender_metrics_robot_timings_metrics_cycle_raw{bs=\"$bs\", robot=\"$robots\"}[$__interval])\nor\nquantile_over_time(1, bs_robot_timings_metrics_cycle_raw{bs=\"$bs\", robot=\"$robots\"}[$__interval])",
     "legendFormat": "p100"
    },
    {
     "expr": "quantile_over_time(0.99, bender_metrics_robot_timings_metrics_cycle_raw{bs=\"$bs\", robot=\"$robots\"}[$__interval])\nor\nquantile_over_time(0.99, bs_robot_timings_metrics_cycle_raw{bs=\"$bs\", robot=\"$robots\"}[$__interval])",
     "legendFormat": "p99"
    },
    {
     "expr": "quantile_over_time(0.95, bender_metrics_robot_timings_metrics_cycle_raw{bs=\"$bs\", robot=\"$robots\"}[$__interval])\nor\nquantile_over_time(0.95, bs_robot_timings_metrics_cycle_raw{bs=\"$bs\", robot=\"$robots\"}[$__interval])",
     "legendFormat": "p95"
    },
    {
     "expr": "quantile_over_time(0.75, bender_metrics_robot_timings_metrics_cycle_raw{bs=\"$bs\", robot=\"$robots\"}[$__interval])\nor\nquantile_over_time(0.75, bs_robot_timings_metrics_cycle_raw{bs=\"$bs\", robot=\"$robots\"}[$__interval])",
     "legendFormat": "p75"
    },
    {
     "expr": "quantile_over_time(0.50, bender_metrics_robot_timings_metrics_cycle_raw{bs=\"$bs\", robot=\"$robots\"}[$__interval])\nor\nquantile_over_time(0.50, bs_robot_timings_metrics_cycle_raw{bs=\"$bs\", robot=\"$robots\"}[$__interval])",
     "legendFormat": "p50"
    },
    {
     "expr": "quantile_over_time(0.25, bender_metrics_robot_timings_metrics_cycle_raw{bs=\"$bs\", robot=\"$robots\"}[$__interval])\nor\nquantile_over_time(0.25, bs_robot_timings_metrics_cycle_raw{bs=\"$bs\", robot=\"$robots\"}[$__interval])",
     "legendFormat": "p25"
    },
    {
     "expr": "quantile_over_time(0.05, bender_metrics_robot_timings_metrics_cycle_raw{bs=\"$bs\", robot=\"$robots\"}[$__interval])\nor\nquantile_over_time(0.05, bs_robot_timings_metrics_cycle_raw{bs=\"$bs\", robot=\"$robots\"}[$__interval])",
     "legendFormat": "p05"
    },
    {
     "expr": "quantile_over_time(0.01, bender_metrics_robot_timings_metrics_cycle_raw{bs=\"$bs\", robot=\"$robots\"}[$__interval])\nor\nquantile_over_time(0.01, bs_robot_timings_metrics_cycle_raw{bs=\"$bs\", robot=\"$robots\"}[$__interval])",
     "legendFormat": "p01"
    }
   ]
  },
  {
   "title": "aftercycle_postorder",
   "type": "candlestick",
   "description": "Start: Конец работы основного цикла.\n\nProcess: Формирование и отправка ордеров в гейты. \n\nEnd: Ордера отправлены в гейт.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "quantile_over_time(1, bender_metrics_internal_exec_delays_aftercycle_postorder_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor\nquantile_over_time(1, bs_internal_exec_delays_aftercycle_postorder_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p100"
    },
    {
     "expr": "quantile_over_time(0.99, bender_metrics_internal_exec_delays_aftercycle_postorder_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor\nquantile_over_time(0.99, bs_internal_exec_delays_aftercycle_postorder_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p99"
    },
    {
     "expr": "quantile_over_time(0.95, bender_metrics_internal_exec_delays_aftercycle_postorder_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(0.95, bs_internal_exec_delays_aftercycle_postorder_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p95"
    },
    {
     "expr": "quantile_over_time(0.75, bender_metrics_internal_exec_delays_aftercycle_postorder_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(0.75, bs_internal_exec_delays_aftercycle_postorder_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p75"
    },
    {
     "expr": "quantile_over_time(0.5, bender_metrics_internal_exec_delays_aftercycle_postorder_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(0.5, bs_internal_exec_delays_aftercycle_postorder_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p50"
    },
    {
     "expr": "quantile_over_time(0.25, bender_metrics_internal_exec_delays_aftercycle_postorder_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(0.25, bs_internal_exec_delays_aftercycle_postorder_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p25"
    },
    {
     "expr": "quantile_over_time(0.05, bender_metrics_internal_exec_delays_aftercycle_postorder_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(0.05, bs_internal_exec_delays_aftercycle_postorder_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p05"
    },
    {
     "expr": "quantile_over_time(0.01, bender_metrics_internal_exec_delays_aftercycle_postorder_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(0.01, bs_internal_exec_delays_aftercycle_postorder_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p01"
    }
   ]
  },
  {
   "title": "postorder_gwwoke",
   "type": "candlestick",
   "description": "Start: Ордера отправлены в гейт. \n\nProcess: Ожидание начала работы гейта.\n\nEnd: Гейт начал отработку.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "quantile_over_time(1, bender_metrics_internal_exec_delays_postorder_gwwoke_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(1, bender_metrics_internal_exec_delays_postorder_gwwoke_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p100"
    },
    {
     "expr": "quantile_over_time(0.99, bender_metrics_internal_exec_delays_postorder_gwwoke_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(0.99, bs_internal_exec_delays_postorder_gwwoke_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p99"
    },
    {
     "expr": "quantile_over_time(0.95, bender_metrics_internal_exec_delays_postorder_gwwoke_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(0.95, bs_internal_exec_delays_postorder_gwwoke_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p95"
    },
    {
     "expr": "quantile_over_time(0.75, bender_metrics_internal_exec_delays_postorder_gwwoke_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(0.75, bs_internal_exec_delays_postorder_gwwoke_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p75"
    },
    {
     "expr": "quantile_over_time(0.5, bender_metrics_internal_exec_delays_postorder_gwwoke_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(0.5, bs_internal_exec_delays_postorder_gwwoke_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p50"
    },
    {
     "expr": "quantile_over_time(0.25, bender_metrics_internal_exec_delays_postorder_gwwoke_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(0.25, bs_internal_exec_delays_postorder_gwwoke_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p25"
    },
    {
     "expr": "quantile_over_time(0.05, bender_metrics_internal_exec_delays_postorder_gwwoke_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(0.05, bs_internal_exec_delays_postorder_gwwoke_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p05"
    },
    {
     "expr": "quantile_over_time(0.01, bender_metrics_internal_exec_delays_postorder_gwwoke_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(0.01, bs_internal_exec_delays_postorder_gwwoke_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p01"
    }
   ]
  },
  {
   "title": "gwwoke_gwsend",
   "type": "candlestick",
   "description": "Start: Гейт начал отработку.\n\nProcess: Обработка ивентов. \n\nEnd: Начало обработки ордеров.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "quantile_over_time(1, bender_metrics_internal_exec_delays_gwwoke_gwsend_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(1, bs_internal_exec_delays_gwwoke_gwsend_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p100"
    },
    {
     "expr": "quantile_over_time(0.99, bender_metrics_internal_exec_delays_gwwoke_gwsend_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(0.99, bs_internal_exec_delays_gwwoke_gwsend_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p99"
    },
    {
     "expr": "quantile_over_time(0.95, bender_metrics_internal_exec_delays_gwwoke_gwsend_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(0.95, bs_internal_exec_delays_gwwoke_gwsend_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p95"
    },
    {
     "expr": "quantile_over_time(0.75, bender_metrics_internal_exec_delays_gwwoke_gwsend_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(0.75, bs_internal_exec_delays_gwwoke_gwsend_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p75"
    },
    {
     "expr": "quantile_over_time(0.5, bender_metrics_internal_exec_delays_gwwoke_gwsend_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(0.5, bs_internal_exec_delays_gwwoke_gwsend_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p50"
    },
    {
     "expr": "quantile_over_time(0.25, bender_metrics_internal_exec_delays_gwwoke_gwsend_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(0.25, bs_internal_exec_delays_gwwoke_gwsend_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p25"
    },
    {
     "expr": "quantile_over_time(0.05, bender_metrics_internal_exec_delays_gwwoke_gwsend_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(0.05, bs_internal_exec_delays_gwwoke_gwsend_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p05"
    },
    {
     "expr": "quantile_over_time(0.01, bender_metrics_internal_exec_delays_gwwoke_gwsend_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(0.01, bs_internal_exec_delays_gwwoke_gwsend_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p01"
    }
   ]
  },
  {
   "title": "gwsend_execth",
   "type": "candlestick",
   "description": "Start: Начало обработки ордеров.\n\nProcess: Проверка ограничений. В случае успеха - формирование ордера для биржи.\n\nEnd: Отправка ордера в систему сетевого взаимодействия.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "quantile_over_time(1, bender_metrics_internal_exec_delays_gwsend_execth_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(1, bs_internal_exec_delays_gwsend_execth_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p100"
    },
    {
     "expr": "quantile_over_time(0.99, bender_metrics_internal_exec_delays_gwsend_execth_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(0.99, bs_internal_exec_delays_gwsend_execth_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p99"
    },
    {
     "expr": "quantile_over_time(0.95, bender_metrics_internal_exec_delays_gwsend_execth_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(0.95, bs_internal_exec_delays_gwsend_execth_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p95"
    },
    {
     "expr": "quantile_over_time(0.75, bender_metrics_internal_exec_delays_gwsend_execth_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(0.75, bs_internal_exec_delays_gwsend_execth_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p75"
    },
    {
     "expr": "quantile_over_time(0.5, bender_metrics_internal_exec_delays_gwsend_execth_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(0.5, bs_internal_exec_delays_gwsend_execth_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p50"
    },
    {
     "expr": "quantile_over_time(0.25, bender_metrics_internal_exec_delays_gwsend_execth_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(0.251, bs_internal_exec_delays_gwsend_execth_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p25"
    },
    {
     "expr": "quantile_over_time(0.05, bender_metrics_internal_exec_delays_gwsend_execth_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(0.05, bs_internal_exec_delays_gwsend_execth_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p05"
    },
    {
     "expr": "quantile_over_time(0.01, bender_metrics_internal_exec_delays_gwsend_execth_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(0.01, bs_internal_exec_delays_gwsend_execth_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])",
     "legendFormat": "p01"
    }
   ]
  },
  {
   "title": "execth_sent",
   "type": "candlestick",
   "description": "Start: Отправка ордера в систему сетевого взаимодействия. \n\nProcess: Формирование сообщения для биржи.\n\nEnd: Сообщение отправлено в сетевую библиотеку.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "quantile_over_time(1, bender_metrics_internal_exec_delays_execth_sent_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(1, bs_internal_exec_delays_execth_sent_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval]) ",
     "legendFormat": "p100"
    },
    {
     "expr": "quantile_over_time(0.99, bender_metrics_internal_exec_delays_execth_sent_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(0.99, bs_internal_exec_delays_execth_sent_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval]) ",
     "legendFormat": "p99"
    },
    {
     "expr": "quantile_over_time(0.95, bender_metrics_internal_exec_delays_execth_sent_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(0.95, bs_internal_exec_delays_execth_sent_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval]) ",
     "legendFormat": "p95"
    },
    {
     "expr": "quantile_over_time(0.75, bender_metrics_internal_exec_delays_execth_sent_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(0.75, bs_internal_exec_delays_execth_sent_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval]) ",
     "legendFormat": "p75"
    },
    {
     "expr": "quantile_over_time(0.5, bender_metrics_internal_exec_delays_execth_sent_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(0.5, bs_internal_exec_delays_execth_sent_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval]) ",
     "legendFormat": "p50"
    },
    {
     "expr": "quantile_over_time(0.25, bender_metrics_internal_exec_delays_execth_sent_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(0.25, bs_internal_exec_delays_execth_sent_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval]) ",
     "legendFormat": "p25"
    },
    {
     "expr": "quantile_over_time(0.05, bender_metrics_internal_exec_delays_execth_sent_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(0.05, bs_internal_exec_delays_execth_sent_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval]) ",
     "legendFormat": "p05"
    },
    {
     "expr": "quantile_over_time(0.01, bender_metrics_internal_exec_delays_execth_sent_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval])\nor quantile_over_time(0.01, bs_internal_exec_delays_execth_sent_raw{bs=\"$bs\", gateway=\"$gateway\"}[$__interval]) ",
     "legendFormat": "p01"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "quantiles(\"GwPDelayPhi\",0.05, 0.95, 0.75, 0.25, sum(bender_metrics_book_delay_gw_to_publisher_raw{bs=\"CMM0\"}[$__range]) by (bs, gateway))",
     "legendFormat": "{{GwPDelayPhi}}-CMM0"
    },
    {
     "expr": "quantiles(\"PToSDelayPhi\", 0.05, 0.95, 0.75, 0.25, sum(bender_metrics_book_delay_publish_to_subscribers_raw{bs=\"CMM0\"}[$__range]) by (bs, gateway))",
     "legendFormat": "__auto"
    },
    {
     "expr": "quantiles(\"PrePhi\",0.05, 0.95, 0.75, 0.25, sum(bender_metrics_robot_timings_metrics_pre_cycle_raw{bs=\"CMM0\"}[$__range]) by (bs, robot))",
     "legendFormat": "__auto"
    },
    {
     "expr": "quantiles(\"CyclePhi\",0.05, 0.95, 0.75, 0.25, sum(bender_metrics_robot_timings_metrics_cycle_raw{bs=\"CMM0\"}[$__range]) by (bs, robot))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}